#ifndef DEFS_H
#define DEFS_H

#define MAX_LINE_LEN 1024
#define MAX_TOK_LEN 256
#define MAX_WORD_LEN 64
#define MAX_PROGRAM_LEN 1024
#define MAX_LABEL_NUM 256
#define MAX_VAR_CNT 256
#define MAX_KV_NUM 256
#define MAX_STATEMENTS_NUM 1024
#define MAX_LABEL_LEN 128
#define MAX_VAL_LEN 256

typedef enum wam_op_t {
	OP_ALLOC,
	OP_DEALLOC,
	OP_CALL,
	OP_NOT_CALL,
	OP_CREATE_VAR,
	OP_GET_CONST,
   	OP_GET_VAL,
	OP_GET_VAR,
	OP_GET_LVL,
	OP_PUT_VAL,
	OP_PUT_VAR,
	OP_PUT_CONST,
	OP_HALT,
	OP_NOOP,
	OP_PROCEED,
	OP_RTRY_ME_ELSE,
	OP_TRUST_ME,
	OP_TRY_ME_ELSE,
	OP_UNI_LIST,
	OP_UNI_STRUC,
	OP_UNI_VAR
} wam_op_t;

#define CALL_CONSULT  	-1
#define CALL_RECONSULT 	-2
#define CALL_LOAD		-3
#define CALL_CALL		-4
#endif
